[package]
name = "shipssignal"
version = "1.2.0"
description = "ShipSignal desktop app"
authors = ["you"]
edition = "2021"

[lib]
name = "shipssignal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-notification = "2"
tauri-plugin-os = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "time"] }
futures-util = "0.3"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
hmac = "0.12"
sha2 = "0.10"
md5 = "0.7"
hex = "0.4"
tauri-plugin-http = { version = "2", features = ["dangerous-settings"] }
